/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dados.Dados;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author afrl1
 */
public class GuardarFicheiro extends javax.swing.JPanel {

    Dados dados;
    javax.swing.JFrame frame;
     /**
      * Creates new form GuardarFicheiro
      */
    public GuardarFicheiro(Dados dados,javax.swing.JFrame frame) {
         initComponents();
         this.dados=dados;
         this.frame=frame;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = (JFileChooser) evt.getSource();
         if (JFileChooser.APPROVE_SELECTION.equals(evt.getActionCommand())) {
             File fileToSave = chooser.getSelectedFile();
             ObjectOutputStream oout = null;
 
         try{
             oout = new ObjectOutputStream(new FileOutputStream(fileToSave));        
             oout.writeObject(dados);
         }catch (FileNotFoundException ex) {
              JOptionPane.showMessageDialog(null, "Erro de ficheiro", "Ficheiro", JOptionPane.ERROR_MESSAGE);   
         }catch (IOException ex) {
             JOptionPane.showMessageDialog(null, "Erro a escrever para ficheiro", "Ficheiro", JOptionPane.ERROR_MESSAGE);     
         }finally{
             if(oout != null)
                 try {
                     oout.close();
                     frame.dispose();
                 } catch (IOException ex) {
                     frame.dispose();
                 }
         }
            
         } else if (JFileChooser.CANCEL_SELECTION.equals(evt.getActionCommand())) {
             frame.dispose();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
